# /docker-compose.yml (Версия с автоматической миграцией при запуске)

# version: '3.8' # Убрано как устаревшее

services:
  # --- База Данных PostgreSQL ---
  db:
    image: postgres:15-alpine
    container_name: aifriend-db
    environment:
      POSTGRES_USER: ai_user
      POSTGRES_PASSWORD: StrongPass
      POSTGRES_DB: ai_drug
    volumes:
      - db_data:/var/lib/postgresql/data
    # ports: # Порт не пробрасываем
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB -q"] # Добавлен флаг -q (quiet)
      interval: 5s # Уменьшен интервал для более быстрой проверки
      timeout: 3s
      retries: 5
      start_period: 10s
    restart: unless-stopped

  # --- Redis (Брокер Celery / Кэш) ---
  redis:
    image: redis:7-alpine
    container_name: aifriend-redis
    command: ["redis-server", "--save", "60", "1", "--loglevel", "warning"]
    volumes:
      - redis_data:/data
    # ports: # Порт не пробрасываем
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s # Уменьшен интервал
      timeout: 3s
      retries: 3
      start_period: 5s
    restart: unless-stopped

  # --- Сервис Миграции (Автоматический Запуск) ---
  migrate:
    container_name: aifriend-migrate
    build:
      context: .
      dockerfile: Dockerfile
    # Используем sh -c для выполнения нескольких команд
    command: >
      sh -c "
        echo 'Migrate service started. Waiting for DB...' &&
        # Цикл ожидания доступности БД (используем pg_isready)
        until pg_isready -h db -U ai_user -d ai_drug -q; do
          echo 'DB is unavailable - sleeping';
          sleep 1;
        done &&
        echo 'DB is ready!' &&
        echo 'Attempting to autogenerate migration (if models changed)...' &&
        # Генерируем миграцию (создаст файл, если есть изменения)
        alembic -c /app/alembic.ini revision --autogenerate -m 'auto-generated changes' &&
        echo 'Applying migrations (upgrade head)...' &&
        # Применяем ВСЕ миграции (включая только что сгенерированную, если она была)
        alembic -c /app/alembic.ini upgrade head &&
        echo 'Migrations finished successfully.'
      "
    env_file:
      # Передаем окружение для доступа к DATABASE_URL ИЛИ переменным интерполяции
      - .env.${ENVIRONMENT}
    depends_on:
      # Зависит от ЗАПУСКА DB, но не от healthcheck, т.к. сам проверяет готовность
      db:
        condition: service_started # Достаточно, чтобы сервис db был запущен
    # Этот сервис должен выполниться и завершиться.
    # Если не указать restart, по умолчанию он 'no'.
    # restart: 'no'

  # --- Веб-сервер FastAPI ---
  web:
    container_name: aifriend-web
    build:
      context: .
      dockerfile: Dockerfile
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"] # Без --reload
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env.${ENVIRONMENT}
    depends_on:
      # Зависим от готовности БД и Redis. migrate выполнится до этого сам.
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    # healthcheck: # Пока закомментирован
    restart: unless-stopped

  # --- Celery Worker ---
  celery:
    container_name: aifriend-celery
    build:
      context: .
      dockerfile: Dockerfile
    command: ["celery", "-A", "app.workers.tasks:celery_app", "worker", "--loglevel=info"]
    volumes:
      - .:/app
    env_file:
      - .env.${ENVIRONMENT}
    depends_on:
      # Зависим от готовности БД и Redis
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    restart: unless-stopped

  # --- Celery Beat (Планировщик) ---
  celery-beat:
    container_name: aifriend-celery-beat
    build:
      context: .
      dockerfile: Dockerfile
    command: ["celery", "-A", "app.workers.tasks:celery_app", "beat", "--loglevel=info"]
    volumes:
      - .:/app
    env_file:
      - .env.${ENVIRONMENT}
    depends_on:
      # Зависим от готовности БД и Redis
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    restart: unless-stopped

# --- Named Volumes ---
volumes:
  db_data:
    driver: local
  redis_data:
    driver: local
