name: Auto-merge Codex PRs

on:
  pull_request:
    types: [labeled]
  schedule:
    - cron: '*/15 * * * *'

jobs:
  automerge:
    runs-on: ubuntu-latest
    if: >
      github.event.label.name == 'codex'
      || github.event_name == 'schedule'
    steps:
      - uses: actions/checkout@v3

      - name: Auto-merge all open Codex PRs
        run: |
          gh auth setup-github-cli
          for pr in $(gh pr list --label codex --state open --json number -q '.[].number'); do
            gh pr merge $pr --merge --delete-branch --auto
          done
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
